language: java

dist: xenial

services:
  - xvfb

addons:
  firefox: "latest"
  
script: mvn clean test

before_install:
  - firefox http://opencart.abstracta.us
  - chmod +x /home/travis/build/germansalinas700/mp/geckodriver
